name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore Matuning/Matuning.csproj

      # Сборка решения
      - name: Build
        run: dotnet build Matuning/Matuning.csproj --configuration Release --no-restore
        